Christ3D.UI.Web/Controllers/StudentController.cs
using System;
using Christ3D.Application.Interfaces;
using Christ3D.Application.ViewModels;
using Christ3D.Domain.Core.Notifications;
using FluentValidation;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace Christ3D.UI.Web.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentAppService _studentAppService;
        IValidator<StudentViewModel> _validator;
        private IMemoryCache _cache;
        // 将领域通知处理程序注入Controller
        private readonly DomainNotificationHandler _notifications;

        public StudentController(IStudentAppService studentAppService, IMemoryCache cache, INotificationHandler<DomainNotification> notifications)
        {
            _studentAppService = studentAppService;
            _cache = cache;
            // 强类型转换
            _notifications = (DomainNotificationHandler)notifications;
        }

        // GET: Student
        public ActionResult Index()
        {
            return View(_studentAppService.GetAll());
        }

        // GET: Student/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentViewModel = _studentAppService.GetById(id.Value);

            if (studentViewModel == null)
            {
                return NotFound();
            }

            return View(studentViewModel);
        }

        // GET: Student/Create
        // 页面
        [Authorize(Policy = "CanWriteStudentData")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Student/Create
        // 方法
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "CanWriteStudentData")]
        public ActionResult Create(StudentViewModel studentViewModel)
        {
            try
            {
                //_cache.Remove("ErrorData");
                //ViewBag.ErrorData = null;
                // 视图模型验证
                if (!ModelState.IsValid)
                    return View(studentViewModel);

                #region 删除命令验证
                ////添加命令验证
                //RegisterStudentCommand registerStudentCommand = new RegisterStudentCommand(studentViewModel.Name, studentViewModel.Email, studentViewModel.BirthDate, studentViewModel.Phone);

                ////如果命令无效，证明有错误
                //if (!registerStudentCommand.IsValid())
                //{
                //    List<string> errorInfo = new List<string>();
                //    //获取到错误，请思考这个Result从哪里来的 
                //    foreach (var error in registerStudentCommand.ValidationResult.Errors)
                //    {
                //        errorInfo.Add(error.ErrorMessage);
                //    }
                //    //对错误进行记录，还需要抛给前台
                //    ViewBag.ErrorData = errorInfo;
                //    return View(studentViewModel);
                //} 
                #endregion

                // 执行添加方法
                _studentAppService.Register(studentViewModel);

                //var errorData = _cache.Get("ErrorData");
                //if (errorData == null)

                // 是否存在消息通知
                if (!_notifications.HasNotifications())
                    ViewBag.Sucesso = "Student Registered!";

                return View(studentViewModel);
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }

        // GET: Student/Edit/5
        [HttpGet]
        [Authorize(Policy = "CanWriteStudentData")]
        public IActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentViewModel = _studentAppService.GetById(id.Value);

            if (studentViewModel == null)
            {
                return NotFound();
            }

            return View(studentViewModel);
        }

        // POST: Student/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "CanWriteStudentData")]
        public IActionResult Edit(StudentViewModel studentViewModel)
        {
            if (!ModelState.IsValid) return View(studentViewModel);

            _studentAppService.Update(studentViewModel);

            if (!_notifications.HasNotifications())
                ViewBag.Sucesso = "Student Updated!";

            return View(studentViewModel);
        }

        // GET: Student/Delete/5
        [Authorize(Policy = "CanWriteOrRemoveStudentData")]
        public IActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var studentViewModel = _studentAppService.GetById(id.Value);

            if (studentViewModel == null)
            {
                return NotFound();
            }

            return View(studentViewModel);
        }

        // POST: Student/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "CanWriteOrRemoveStudentData")]
        public IActionResult DeleteConfirmed(Guid id)
        {
            _studentAppService.Remove(id);

            if (!_notifications.HasNotifications())
                return View(_studentAppService.GetById(id));

            ViewBag.Sucesso = "Student Removed!";
            return RedirectToAction("Index");
        }

        [Route("history/{id:guid}")]
        public JsonResult History(Guid id)
        {
            var studentHistoryData = _studentAppService.GetAllHistory(id);
            return Json(studentHistoryData);
        }
    }
}

Christ3D.UI.Web/ViewComponents/AlertsViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Christ3D.Domain.Core.Notifications;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace Christ3D.UI.Web.ViewComponents
{
    public class AlertsViewComponent : ViewComponent
    {
        // 缓存注入，为了收录信息（错误方法，以后会用通知，通过领域事件来替换）
        // private IMemoryCache _cache;

        // 领域通知处理程序
        private readonly DomainNotificationHandler _notifications;

        // 构造函数注入
        public AlertsViewComponent(INotificationHandler<DomainNotification> notifications)
        {
            //_cache = cache;
            _notifications = (DomainNotificationHandler)notifications;
        }


        /// <summary>
        /// Alerts 视图组件
        /// 可以异步，也可以同步，注意方法名称，同步的时候是Invoke
        /// 我写异步是为了为以后做准备
        /// </summary>
        /// <returns></returns>
        public async Task<IViewComponentResult> InvokeAsync()
        {
            //// 获取到缓存中的错误信息
            //var errorData = _cache.Get("ErrorData");
            //var notificacoes = await Task.Run(() => (List<string>)errorData);
            //// 遍历添加到ViewData.ModelState 中
            //notificacoes?.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c));

            // 从通知处理程序中，获取全部通知信息，并返回给前台
            var notificacoes = await Task.FromResult((_notifications.GetNotifications()));
            notificacoes.ForEach(c => ViewData.ModelState.AddModelError(string.Empty, c.Value));

            return View();
        }
    }
}

Christ3D.UI.Web/Views/Student/Create.cshtml
@model StudentViewModel
@{
    ViewData["Title"] = "Register new Student";
}
<h2>@ViewData["Title"]</h2>
<form asp-action="Create">
    <div class="form-horizontal">
        <hr />
        @* 将经典验证摘要替换为自定义视图组件作为标记助手 *@

        @*方式一(可用，但不推荐) @await Component.InvokeAsync("Alerts")*@

        <!-- 如果使用这个方法，请记得在_ViewImports.cshtml 中，导入@addTagHelper "*, Christ3D.UI.Web" -->
        <vc:alerts />

        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BirthDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
        </div>

        @*<div class="form-group">
            <label asp-for="Address.Province" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address.Province" class="form-control" />
                <span asp-validation-for="Address.Province" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address.City" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address.County" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address.County" class="form-control" />
                <span asp-validation-for="Address.County" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Address.Street" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Address.Street" class="form-control" />
                <span asp-validation-for="Address.Street" class="text-danger"></span>
            </div>
        </div>*@

        <div class="form-group">
            <label asp-for="Province" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Province" class="form-control" />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="City" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="County" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="County" class="form-control" />
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Street" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>

Christ3D.UI.Web/Views/Student/Delete.cshtml
@model StudentViewModel
@{
    ViewData["Title"] = "Delete Student";
}
<h2>@ViewData["Title"]</h2>
<form asp-action="Delete">
    <vc:alerts />
    <h3>Are you sure you want to delete the @Model.Name?</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Email)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.Email)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.BirthDate)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.BirthDate)
            </dd>
        </dl>

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-info">Back to List</a>
        </div>
    </div>
</form>

Christ3D.UI.Web/Views/Student/Details.cshtml
@model StudentViewModel
@{
    ViewData["Title"] = "Student Details";
}
<h2>@ViewData["Title"]</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Province)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Province)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.County)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.County)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-warning">Edit</a>
    <a asp-action="Index" class="btn btn-info">Back to List</a>
</div>

Christ3D.UI.Web/Views/Student/Edit.cshtml
@model StudentViewModel
@{
    ViewData["Title"] = "Edit Student";
}
<h2>@ViewData["Title"]</h2>
<form asp-action="Edit">
    <div class="form-horizontal">
        <hr />
        <input type="hidden" asp-for="Id" />
        @* Replacing classic Validation Summary to Custom ViewComponent as TagHelper *@
        <vc:alerts />

        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Email" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Phone" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="BirthDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="BirthDate" class="form-control" />
                <span asp-validation-for="BirthDate" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Province" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Province" class="form-control" />
                <span asp-validation-for="Province" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="City" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="County" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="County" class="form-control" />
                <span asp-validation-for="County" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Street" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
                <a asp-action="Index" class="btn btn-info">Back to List</a>
            </div>
        </div>
    </div>
</form>

Christ3D.UI.Web/Views/Student/Index.cshtml
@model IEnumerable<StudentViewModel>
@{
    ViewData["Title"] = "Student Management";
}
<div>
    <h2>@ViewData["Title"]</h2>
</div>
<hr />
<div class="row">
    <div class="col-md-12">
        <div>
            <div class="pull-left">
                <a asp-action="Create" class="btn btn-primary">
                    <span title="Register New" class="glyphicon glyphicon-plus-sign"></span> Register New
                </a>
            </div>
        </div>
    </div>
</div>
<br />
<div class="panel panel-default">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.BirthDate)
                </th>
                <th>户籍</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BirthDate)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.Address.Province)
                            @Html.DisplayFor(modelItem => item.Address.City)
                            @Html.DisplayFor(modelItem => item.Address.County)
                            @Html.DisplayFor(modelItem => item.Address.Street)*@

                        @Html.DisplayFor(modelItem => item.Province)
                        @Html.DisplayFor(modelItem => item.County)
                        @Html.DisplayFor(modelItem => item.City)
                        @Html.DisplayFor(modelItem => item.Street)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" title="Edit" class="btn btn-warning">
                            <span class="glyphicon glyphicon-pencil"></span>
                        </a>

                        <a asp-action="Details" asp-route-id="@item.Id" title="Details" class="btn btn-primary">
                            <span class="glyphicon glyphicon-search"></span>
                        </a>

                        <a asp-action="Delete" asp-route-id="@item.Id" title="Delete" class="btn btn-danger">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>

                        <button type="button" class="btn btn-purple viewbutton" title="History" data-id="@item.Id" data-toggle="modal" data-target="#studentHistory">
                            <span class="glyphicon glyphicon-time"></span>
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="modal fade" id="studentHistory" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">student Data History</h4>
            </div>
            <div class="modal-body">
                <p id="studentHistoryData"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
@section scripts
    {
    <script type="text/javascript">

        $(".viewbutton").on("click", function () {
            var customerId = $(this).data('id');
            $("#studentHistoryData").html("");
            $.ajax({
                url: "/history/" + customerId,
                cache: false
            }).done(function (data) {
                var formatHtml = "<table class='table table-striped'>";
                formatHtml += "<thead><th>Action</th><th>When</th><th>Id</th><th>Name</th><th>E-mail</th><th>Birth Date</th><th>By User</th></thead>";
                
                for (var i = 0; i < data.length; i++) {
                    var change = data[i];
                    formatHtml += "<tr>";
                    formatHtml += "<td>" + change.action + "</td>";
                    formatHtml += "<td>" + change.when + "</td>";
                    formatHtml += "<td>" + change.id + "</td>";
                    formatHtml += "<td>" + change.name + "</td>";
                    formatHtml += "<td>" + change.email + "</td>";
                    formatHtml += "<td>" + change.birthDate + "</td>";
                    formatHtml += "<td>" + change.who + "</td>";
                    formatHtml += "</tr>";
                }
                formatHtml += "</table>";
                $("#studentHistoryData").html(formatHtml);
            });
        });
    </script>
}